version: "3.7"
x-nacos-common: &macos-common
  image: nacos/nacos-server:v2.2.0

  environment:
    # 集群模式
    MODE: cluster
    # -Xms
    JVM_XMS: 1g
    JVM_XMX: 1g
    JVM_XMN: 1g
    # -XX:MetaspaceSize
    JVM_MS: 128m
    # -XX:MaxMetaspaceSize
    JVM_MMS: 320m

    # 集群地址
    NACOS_SERVERS: nacos1:8848 nacos2:8848 nacos3:8848
    # 数据库 连接地址
    MYSQL_SERVICE_HOST: mysql
    # 数据库库名   nacos_db
    MYSQL_SERVICE_DB_NAME: nacos_db
    # 数据库端口
    MYSQL_SERVICE_PORT: 3306
    # 数据库 用户名
    MYSQL_SERVICE_USER: nacos
    # 数据库密码
    MYSQL_SERVICE_PASSWORD: 3ZctPfM8cqTh2YYrWJV4ubKvXUx9H7S
    # 支持IP还是域名模式  ostname(主机名)/ip 默认 ip
    PREFER_HOST_MODE: hostname
    # 是否开启集群嵌入式存储模式	embedded 默认 : none
    EMBEDDED_STORAGE: none
  # 定义容器重启策略(在使用 swarm 部署时将忽略该选项, 在 swarm 使用 restart_policy 代替 restart)
  #  no                    # 禁止自动重启容器(默认)
  # always                # 无论如何容器都会重启
  # on-failure            # 当出现 on-failure 报错时, 容器重新启动
  restart: always
  volumes:
    - ./init.d/application.properties:/home/nacos/init.d/application.properties
    - ./conf/application.properties:/home/nacos/conf/application.properties
  expose:
    - "8848"
    - "9848"
    - "7848"
  depends_on: # 定义容器启动顺序 (此选项解决了容器之间的依赖关系， 此选项在 v3 版本中 使用 swarm 部署时将忽略该选项)
    - mysql
x-pig-common: &pig-common
  environment:
    - NACOS_ADDR: nacos1:8848 nacos2:8848 nacos3:8848
  restart: always
services:
  nacos1:
    <<: *macos-common
    hostname: nacos1
    container_name: nacos1
  nacos2:
    <<: *macos-common
    hostname: nacos2
    container_name: nacos2

  nacos3:
    <<: *macos-common
    hostname: nacos3
    container_name: nacos3



  mysql:
    container_name: mysql
    image: nacos/nacos-mysql:8.0.16
    environment:
      # mysql root密码
      - MYSQL_ROOT_PASSWORD=Xcgn5uG5yyBcPXYrjvyw3Rhs7bYmENGg
      # 创建数据库
      - MYSQL_DATABASE=nacos_db
      # mysql用户名
      - MYSQL_USER=nacos
      # mysql密码f
      - MYSQL_PASSWORD=3ZctPfM8cqTh2YYrWJV4ubKvXUx9H7S
    volumes:
      - ./repository/mysql:/var/lib/mysql  # mysql 文件应射
    ports:
      - "3306:3306"
# * nacos部分版本需要在config_info和his_config_info两个配置表中增加
  #  encrypted_data_key字段。
  #* 确认我的两个表中原本已经有了这两个字段。
  #* 添加配置依然会提示以上问题。



  # 普罗米修斯 数据监控
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - nacos1
      - nacos2
      - nacos3
    restart: on-failure
  # 监控工具
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    restart: on-failure
    depends_on:
      - prometheus



  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/tcp.d/:/etc/nginx/tcp.d/
    ports:
      - "8848:8848"
      - "9848:9848"
      - "7848:7848"
    depends_on:
      - grafana

#  nacos.security.ignore.urls=${NACOS_SECURITY_IGNORE_URLS:/,/error,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.ico,/console-fe/public/**,/v1/auth/**,/v1/console/health/**,/actuator/**,/v1/console/server/**}
