= gitHub Action - workflow 概念和基本操作

===== workflow 文件

* GitHub Actions 的配置文件叫做 workflow文件，存放在代码仓库的.github/workflows/目录下。 比如写一个first.yaml文件，存储的目录就是.github/workflows/first.yaml
* workflow/下的文件采用 YAML 格式，文件名可以任意取，但是后缀名统一为.yml或者yaml， 比如foo.yml。一个库可以有多个 workflow 文件。 GitHub 只要发现.github/workflows目录下里面有.yml文件，就会自动运行该文件

====== workflow/下的文件的配置字段非常多，详见官方文档。下面是一些基本字段。

*name*

name字段是 workflow 的名称。如果省略该字段，默认为当前 workflow 的文件名。

[source,yaml]
----
name: GitHub Actions Test
----

*on*

* on字段指定触发 workflow 的条件，通常是某些事件。

[source,yaml]
----
on: push #  push事件触发 workflow
----

* on字段也可以是事件的数组。

[source,yaml]
----
on: [push, pull_request] #push事件或pull_request事件都可以触发 workflow。]
----

* 完整的事件列表，请查看 https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows[官方文档]。除了代码库事件，GitHub Actions 也支持外部事件触发，或者定时运行。

*on.
.*

** 指定触发事件时，可以限定分支或标签。

[source,yaml]
----
on:
  push:
    branches:
      - master # 上面代码指定，只有master分支发生push事件时，才会触发 workflow。
----

*jobs..name*

workflow 文件的主体是jobs字段，表示要执行的一项或多项任务。

jobs字段里面，需要写出每一项任务的job_id，具体名称自定义。job_id里面的name字段是任务的说明。

[source,yaml]
----
jobs:
  my_first_job:
    name: My first job
  my_second_job:
    name: My second job
----

上面代码的jobs字段包含两项任务，job_id分别是my_first_job和my_second_job。

*jobs..needs*

needs字段指定当前任务的依赖关系，即运行顺序。

[source,yaml]
----
jobs:
  job1:
  job2:
    needs: job1
  job3:
    needs: [job1, job2]
----

上面代码中，__job1__必须先于__job2__完成，而__job3__等待__job1__和__job2__的完成才能运行。因此，这个 workflow 的运行顺序依次为：job1、job2、job3。

*jobs..runs-on*

runs-on字段指定运行所需要的虚拟机环境。它是必填字段。目前可用的虚拟机如下。

下面代码指定虚拟机环境为ubuntu-18.04。

[source,yaml]
----
runs-on: ubuntu-18.04
----

*jobs..steps*
steps字段指定每个 Job 的运行步骤，可以包含一个或多个步骤。每个步骤都可以指定以下三个字段。

----
jobs.<job_id>.steps.name：步骤名称。
jobs.<job_id>.steps.run：该步骤运行的命令或者 action。
jobs.<job_id>.steps.env：该步骤所需的环境变量。
----

===== 下面是一个完整的 workflow 文件的范例。

[source,yaml]
----
name: Greeting from Mona
on: push

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Mona
        MIDDLE_NAME: The
        LAST_NAME: Octocat
      run: |
        echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
----

上面代码中，steps字段只包括一个步骤。该步骤先注入四个环境变量，然后执行一条 Bash 命令，当代码push时触发这个workflow。




